version: "3.9"
services:

  redis:
    image: redis
    container_name: redis
    ports:
     - "6379:6379"
    command:  redis-server --save 60 1 --loglevel warning 
    restart: always

  django:
    build: .
    container_name: django
    command: gunicorn -c /app/gunicorn.conf.py core.wsgi:application
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  # worker-celery:
  #   build: .
  #   volumes:
  #     - ./core:/app
  #   command: celery -A core worker -l INFO
  #   depends_on:
  #     - django
  #     - redis

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - django

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

volumes:
  postgres_data:
  static_volume:
  media_volume:
  smtp4dev-data: